kind: pipeline
type: docker
name: automation_poc_pipeline

trigger:
  branch:
  - develop
  event:
  - pull_request
  - tag

platform:
  os: linux
  arch: amd64


steps:
- name: Install packages
  image: node:16
  commands:
  - npm install

- name: Build
  image: node:16
  commands:
  - npm run build

- name: Lint and test
  image: node:16
  commands: 
  - npx turbo run lint test

- name : AWS CDK Deploy
  image: node:16
  when:
    ref:
    - refs/tags/*
    branch:
    - develop

  environment:
    CDK_AWS_ACCOUNT_ID:
      from_secret: CDK_AWS_ACCOUNT_ID
    CDK_AWS_REGION: us-west-2
    CDK_VPC_ID:
      from_secret: CDK_VPC_ID
    CDK_STORAGE_PREFIX_CUCUMBER: /cucumber
    DB_HOST:
      from_secret: DB_HOST
    DB_PORT: 3306
    DB_USERNAME: admin
    DB_PASSWORD:
      from_secret: DB_PASSWORD
    DB_NAME: qa_reports
    PERSISTENCE_LAMBDA_TIMEOUT: 30
    FORMAT_LAMBDA_TIMEOUT: 60
    SCREENSHOT_BUCKET_NAME: qa-report-poc-federico-screenshots
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION:
      from_secret: AWS_DEFAULT_REGION

  commands: 
  - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
  - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
  - npm run cdk:diff
  - npm run deploy